### ISSUE TITLE
ferium-gui

### ISSUE THREAD

**Issue by alikindsys** [roridev/next#10]
A gui for [libium](https://github.com/gorilla-devs/libium)*, cause ferium is the CLI.

Likely written in rust

<sub> note: **nothing on this page is related to the unofficial quilt community launcher project** (from now hereby called ~~"unnamed launcher project":tm:~~ Helix won :partying_face: ). this is a personal thing, and, while i also work on the HelixLauncher this idea of a libium gui frontent predates it (as seen by the issue creation date). this *may* stop being a "libium frontend" and just become a `libhelix` frontend as helix develops.</sub>

<sub> This project may also just become a part of helix on its entirety and be closed cause "helix does that already lmao" </sub>

Features of this thing and projects that already do that
---
- Being able to download modpacks - `multimc`, `ferium`, `packwiz, with packwiz-downloader`, `prism`
- Being able to add/remove aditional mods to modpacks - `multimc`, `prism`
- Being able to update modpacks - `ferium`, `packwiz`, `prism`
- Its a GUI - `multimc` , `prism`
- Being able to create modpacks - `packwiz`, `multimc`, `ferium`, `prism`
- Being able to add "layers" of mods on top of modpacks, as to customize them/debug - none.

Tf are layers
---
Crazy shower thought i had that works like layers in image/video editing software.  
You'd have a base modpack, and from that you add layers that can add/remove mods.  
Layers will be updated first without needing an oficial update from the modpack authors, since they're local to the machine.  
Once a modpack updates, your layer will be checked for conflicts in case the modpack author added a mod that depends on a mod you removed and you'd be promted if you want to add that conflicting mod and its dependencies or not.  
In that sense, you'd be able to mess with your modpack as much as you want, and be able to easily revert to the official one in case you broke something.

Stylesheet
---
**https://www.figma.com/file/cYJhfiWiW6W0PWx1aWTyr0/**

**Comment by alikindsys** [comment]
Base `modpack.umf.toml` format
---
```toml
# Universal Modpack Format 
[meta]
# The base modpack format
# Valid values:
# modrinth - modrinth's .mrpack
# curseforge - curseforge's manifest.json
# packwiz - packwiz's own format (default)
base-format = "modrinth:1.0"
hash = ""

[modrinth]
id = "cEfTr5WJ"
side = ["client"]

[modrinth.meta]
hash = ""
download-id = ""
version = ""

[versions]
quilt = ""
minecraft = ""

[[layers]]
hash = ""
file = ""
enabled = true
```

**Comment by alikindsys** [comment]
Base `name.layer.toml` format
---
```toml
# Layer Format
[meta]
name = ""
author = ""
# Optional array. Used for resolving mods
supported-versions = ["1.19","1.19.1"] 

[[files]]
# Uses the same format as packwiz metadata files
file = "mod.pw.toml"
hash = ""
metafile = true

[[files]]
file = "mod.jar"
hash = ""
metafile = false

# Mods that were manually removed on this layer
[[removed]]
file = "mod.jar"
hash = ""
metafile = false
```
